// Shreeji Hero Showroom ERP - Comprehensive Realistic Mock Data

import {
  UserProfile,
  Customer,
  CustomerVehicle,
  VehicleUnit,
  Lead,
  JobCard,
  SparePart,
  Invoice,
  NotificationItem,
} from '@/types';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'usr_admin',
    employeeCode: 'EMP-1001',
    name: 'Rajesh Sharma',
    email: 'rajesh@shreejihero.com',
    phone: '+91 98765 43210',
    role: 'ADMIN',
    branchId: null, // Cross-branch access
    branchName: 'All Branches (HQ)',
    department: 'Executive',
    designation: 'Managing Director & Dealer Principal',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_manager_hlv',
    employeeCode: 'EMP-1002',
    name: 'Vikram Singh',
    email: 'vikram@shreejihero.com',
    phone: '+91 98765 43211',
    role: 'SHOWROOM_MANAGER',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Operations',
    designation: 'General Showroom Manager',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_sales_amit',
    employeeCode: 'EMP-1003',
    name: 'Amit Verma',
    email: 'amit@shreejihero.com',
    phone: '+91 98765 43212',
    role: 'SALES_EXECUTIVE',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Sales',
    designation: 'Senior Sales Consultant',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_reception_pooja',
    employeeCode: 'EMP-1004',
    name: 'Pooja Sharma',
    email: 'pooja@shreejihero.com',
    phone: '+91 98765 43213',
    role: 'FRONT_DESK',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Front Desk',
    designation: 'Front Desk & Guest Executive',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_srv_mgr_sandeep',
    employeeCode: 'EMP-1005',
    name: 'Sandeep Kumar',
    email: 'sandeep@shreejihero.com',
    phone: '+91 98765 43214',
    role: 'SERVICE_MANAGER',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Workshop',
    designation: 'Workshop & Service Floor Manager',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_srv_adv_kiran',
    employeeCode: 'EMP-1006',
    name: 'Kiran Solanki',
    email: 'kiran@shreejihero.com',
    phone: '+91 98765 43215',
    role: 'SERVICE_ADVISOR',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Workshop',
    designation: 'Customer Service Advisor',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_accountant_neha',
    employeeCode: 'EMP-1007',
    name: 'Neha Gupta',
    email: 'neha@shreejihero.com',
    phone: '+91 98765 43216',
    role: 'ACCOUNTANT',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Finance',
    designation: 'Chief Dealership Accountant',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_inv_mohit',
    employeeCode: 'EMP-1008',
    name: 'Mohit Verma',
    email: 'mohit@shreejihero.com',
    phone: '+91 98765 43217',
    role: 'INVENTORY_MANAGER',
    branchId: 'br_halvad',
    branchName: 'Halvad Branch',
    department: 'Inventory & Spares',
    designation: 'Inventory & Spares Head',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
];

export const MOCK_CUSTOMERS: (Customer & { vehicles: CustomerVehicle[] })[] = [
  {
    id: 'cst_1024',
    customerCode: 'SHR-1024',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh.kumar@example.com',
    address: '12, Shanti Nagar Society, Near SBI Bank',
    city: 'Halvad',
    state: 'Gujarat',
    pincode: '363330',
    branchId: 'br_halvad',
    status: 'ACTIVE',
    notes: 'Loyal customer. Enquired about exchange bonus for Xpulse 200.',
    createdAt: '2023-01-15T10:00:00Z',
    vehicles: [
      {
        id: 'veh_splendor_1024',
        customerId: 'cst_1024',
        registrationNumber: 'GJ-36-AB-1234',
        modelName: 'Hero Splendor+',
        variantName: 'Drum Self Cast',
        color: 'Black with Sports Red',
        vinNumber: 'MBLHAW14XN9001024',
        engineNumber: 'HA10EHN001024',
        purchaseDate: '2023-01-15T10:00:00Z',
        warrantyUntil: '2028-01-14T10:00:00Z',
        status: 'ACTIVE',
        imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'cst_1025',
    customerCode: 'SHR-1025',
    name: 'Suresh Patel',
    phone: '+91 98765 43218',
    email: 'suresh.patel@example.com',
    address: 'Plot 44, GIDC Industrial Estate',
    city: 'Halvad',
    state: 'Gujarat',
    pincode: '363330',
    branchId: 'br_halvad',
    status: 'ACTIVE',
    createdAt: '2023-04-20T11:30:00Z',
    vehicles: [
      {
        id: 'veh_passion_1025',
        customerId: 'cst_1025',
        registrationNumber: 'GJ-36-XY-9876',
        modelName: 'Hero Passion Pro',
        variantName: 'Disc Self Cast',
        color: 'Sports Red',
        vinNumber: 'MBLHAW14XN9001025',
        engineNumber: 'HA10EHN001025',
        purchaseDate: '2023-04-20T11:30:00Z',
        warrantyUntil: '2028-04-19T11:30:00Z',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'cst_1026',
    customerCode: 'SHR-1026',
    name: 'Mahesh Shah',
    phone: '+91 98765 43219',
    email: 'mahesh.shah@example.com',
    address: 'Opposite APMC Market Yard',
    city: 'Halvad',
    state: 'Gujarat',
    pincode: '363330',
    branchId: 'br_halvad',
    status: 'ACTIVE',
    createdAt: '2023-08-10T14:15:00Z',
    vehicles: [
      {
        id: 'veh_glamour_1026',
        customerId: 'cst_1026',
        registrationNumber: 'GJ-13-CD-5566',
        modelName: 'Hero Glamour XTEC',
        variantName: 'Disc Brake',
        color: 'Nexus Blue',
        vinNumber: 'MBLHAW14XN9001026',
        engineNumber: 'HA10EHN001026',
        purchaseDate: '2023-08-10T14:15:00Z',
        warrantyUntil: '2028-08-09T14:15:00Z',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'cst_1027',
    customerCode: 'SHR-1027',
    name: 'Dinesh Jha',
    phone: '+91 98765 43220',
    email: 'dinesh.jha@example.com',
    address: 'Near Dhangadhra Bypass Highway',
    city: 'Halvad',
    state: 'Gujarat',
    pincode: '363330',
    branchId: 'br_halvad',
    status: 'ACTIVE',
    createdAt: '2024-02-05T09:45:00Z',
    vehicles: [
      {
        id: 'veh_hf_1027',
        customerId: 'cst_1027',
        registrationNumber: 'GJ-13-EF-1122',
        modelName: 'Hero HF Deluxe',
        variantName: 'Self Start Drum Alloy',
        color: 'Canvas Black',
        vinNumber: 'MBLHAW14XN9001027',
        engineNumber: 'HA10EHN001027',
        purchaseDate: '2024-02-05T09:45:00Z',
        warrantyUntil: '2029-02-04T09:45:00Z',
        status: 'ACTIVE',
      },
    ],
  },
];

export const MOCK_VEHICLE_UNITS: VehicleUnit[] = [
  {
    id: 'vu_01',
    vin: 'MBLHAW14XN9XXXXX1',
    engineNumber: 'HA10EHNXXXXX1',
    modelName: 'Splendor Plus XTEC',
    variantName: 'Drum Self Cast',
    color: 'Black Nexus Blue',
    branchId: 'br_halvad',
    branchName: 'Halvad',
    status: 'AVAILABLE',
    purchasePrice: 65000,
    sellingPrice: 79900,
    arrivalDate: '2024-05-10T10:00:00Z',
  },
  {
    id: 'vu_02',
    vin: 'MBLHBW14XN9XXXXX2',
    engineNumber: 'HB10EHNXXXXX2',
    modelName: 'HF Deluxe',
    variantName: 'Kick Start Drum Spoke',
    color: 'Heavy Grey with Green',
    branchId: 'br_halvad',
    branchName: 'Halvad',
    status: 'RESERVED',
    purchasePrice: 48000,
    sellingPrice: 59900,
    arrivalDate: '2024-05-11T12:00:00Z',
  },
  {
    id: 'vu_03',
    vin: 'MBLHCW14XN9XXXXX3',
    engineNumber: 'HC10EHNXXXXX3',
    modelName: 'Xpulse 200 4V',
    variantName: 'Disc Brake',
    color: 'Matte Nexus Blue',
    branchId: 'br_halvad',
    branchName: 'Halvad',
    status: 'SOLD',
    purchasePrice: 115000,
    sellingPrice: 145000,
    arrivalDate: '2024-05-01T08:00:00Z',
  },
  {
    id: 'vu_04',
    vin: 'MBLHAW14XN9XXXXX4',
    engineNumber: 'HA10EHNXXXXX4',
    modelName: 'Splendor Plus',
    variantName: 'Drum Self Cast',
    color: 'Sports Red Black',
    branchId: 'br_halvad',
    branchName: 'Halvad',
    status: 'AVAILABLE',
    purchasePrice: 63000,
    sellingPrice: 77500,
    arrivalDate: '2024-05-12T14:30:00Z',
  },
  {
    id: 'vu_05',
    vin: 'MBLHBW14XN9XXXXX5',
    engineNumber: 'HB10EHNXXXXX5',
    modelName: 'HF Deluxe',
    variantName: 'Self Start Drum Alloy',
    color: 'Canvas Black',
    branchId: 'br_halvad',
    branchName: 'Halvad',
    status: 'AVAILABLE',
    purchasePrice: 52000,
    sellingPrice: 64500,
    arrivalDate: '2024-05-14T09:15:00Z',
  },
  {
    id: 'vu_06',
    vin: 'MBLHDW14XN9XXXXX6',
    engineNumber: 'HD10EHNXXXXX6',
    modelName: 'Xtreme 160R 4V',
    variantName: 'Double Disc ABS',
    color: 'Blazing Sports Red',
    branchId: 'br_dhangadhra',
    branchName: 'Dhangadhra',
    status: 'AVAILABLE',
    purchasePrice: 102000,
    sellingPrice: 128000,
    arrivalDate: '2024-05-13T11:00:00Z',
  },
];

export const MOCK_JOB_CARDS: JobCard[] = [
  {
    id: 'jc_8901',
    jobCardNumber: 'JC-8901',
    customerName: 'Ramesh Patel',
    phone: '+91 98765 43210',
    vehicleRegNumber: 'GJ-13-AB-1234',
    vehicleModel: 'Splendor Plus',
    branchId: 'br_halvad',
    advisorName: 'Kiran Solanki',
    technicianName: 'Amit K.',
    complaints: 'Engine knocking noise during cold start; Front brake vibration',
    findings: 'Engine oil degraded. Brake shoe worn out.',
    status: 'IN_PROGRESS',
    estDelivery: '14:30 Today',
    totalLabour: 450,
    totalParts: 650,
    totalAmount: 1100,
    createdAt: '2024-05-15T09:30:00Z',
  },
  {
    id: 'jc_8902',
    jobCardNumber: 'JC-8902',
    customerName: 'Suresh Desai',
    phone: '+91 98765 43221',
    vehicleRegNumber: 'GJ-36-XY-9876',
    vehicleModel: 'Passion Pro',
    branchId: 'br_halvad',
    advisorName: 'Kiran Solanki',
    technicianName: undefined,
    complaints: '2nd Free Service; Chain tightening and general lubrication',
    status: 'CHECKED_IN',
    estDelivery: 'Pending Est.',
    totalLabour: 0,
    totalParts: 380,
    totalAmount: 380,
    createdAt: '2024-05-15T10:15:00Z',
  },
  {
    id: 'jc_8899',
    jobCardNumber: 'JC-8899',
    customerName: 'Mahesh Shah',
    phone: '+91 98765 43219',
    vehicleRegNumber: 'GJ-13-CD-5566',
    vehicleModel: 'Glamour XTEC',
    branchId: 'br_halvad',
    advisorName: 'Kiran Solanki',
    technicianName: 'Vikram P.',
    complaints: 'Periodic Maintenance Service; Oil change and wash',
    status: 'READY_FOR_DELIVERY',
    estDelivery: 'Ready for Pickup',
    totalLabour: 350,
    totalParts: 780,
    totalAmount: 1130,
    createdAt: '2024-05-15T08:30:00Z',
  },
  {
    id: 'jc_8895',
    jobCardNumber: 'JC-8895',
    customerName: 'Dinesh Jha',
    phone: '+91 98765 43220',
    vehicleRegNumber: 'GJ-13-EF-1122',
    vehicleModel: 'HF Deluxe',
    branchId: 'br_halvad',
    advisorName: 'Kiran Solanki',
    technicianName: 'Amit K.',
    complaints: 'Self start not working; Battery check',
    status: 'IN_PROGRESS',
    estDelivery: '16:00 Today',
    totalLabour: 200,
    totalParts: 1200,
    totalAmount: 1400,
    createdAt: '2024-05-15T11:00:00Z',
  },
];

export const MOCK_SPARE_PARTS: SparePart[] = [
  {
    id: 'sp_01',
    partNumber: 'SP-ENG-4T',
    name: 'Engine Oil 4T Plus (1L)',
    category: 'Lubricant',
    brand: 'Hero Genuine Parts',
    unitPrice: 450,
    costPrice: 320,
    currentStock: 45,
    minStockLevel: 10,
    branchId: 'br_halvad',
  },
  {
    id: 'sp_02',
    partNumber: 'SP-BRK-102',
    name: 'Brake Pad Set (Front)',
    category: 'Brakes',
    brand: 'Hero Genuine Parts',
    unitPrice: 320,
    costPrice: 210,
    currentStock: 8,
    minStockLevel: 10,
    branchId: 'br_halvad',
  },
  {
    id: 'sp_03',
    partNumber: 'SP-FLT-301',
    name: 'Air Filter Element',
    category: 'Filters',
    brand: 'Hero Genuine Parts',
    unitPrice: 180,
    costPrice: 110,
    currentStock: 3,
    minStockLevel: 5,
    branchId: 'br_halvad',
  },
  {
    id: 'sp_04',
    partNumber: 'SP-SPK-900',
    name: 'Spark Plug NGK CR7HSA',
    category: 'Electricals',
    brand: 'Hero Genuine Parts',
    unitPrice: 140,
    costPrice: 90,
    currentStock: 22,
    minStockLevel: 10,
    branchId: 'br_halvad',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Vehicle Sold: Splendor+',
    message: 'Halvad Branch • RTO document registration pending for customer Suresh Patel.',
    type: 'LEAD',
    isRead: false,
    timeAgo: '10 mins ago',
  },
  {
    id: 'notif_02',
    title: 'New Walk-in Registered',
    message: 'Front Desk logged inquiry for Xpulse 200 4V (Dinesh Kumar).',
    type: 'LEAD',
    isRead: false,
    timeAgo: '45 mins ago',
  },
  {
    id: 'notif_03',
    title: 'Service Completed: GJ36AB1234',
    message: 'Paid service finished. Invoice generated for ₹1,130.',
    type: 'SERVICE',
    isRead: true,
    timeAgo: '2 hours ago',
  },
  {
    id: 'notif_04',
    title: 'Low Stock Alert: Air Filter Element',
    message: 'Stock at Halvad Branch is 3 units (below threshold of 5).',
    type: 'INVENTORY',
    isRead: false,
    timeAgo: '5 hours ago',
  },
];
